name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0' # once a week

defaults:
  run:
    shell: bash # required for snok/install-poetry on windows

env:
  POETRY_VERSION: 1.8.2

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
      - name: Install dependencies
        run: poetry install
      - name: Check formatting
        run: poetry run black --check .
      - name: Check import order
        run: poetry run isort --check-only .
      - name: Check code style
        run: poetry run flake8 .
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-latest'
          - 'windows-latest'
        python:
          - '3.8'
          - '3.11'
        mkdocs:
          - '1.3'
          - '1.4'
          - '1.6'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
      - name: Install dependencies
        run: poetry install
      - name: Install specific mkdocs version
        run: poetry add mkdocs@${{ matrix.mkdocs }}
      - name: Run tests
        run: poetry run pytest
